name: metrics-server
title: Metrics server
type: infrastructure
scalable: false
helm:
  name: metrics-server
  source: https://kubernetes-sigs.github.io/metrics-server
  chart: metrics-server/metrics-server
  version: 3.12.1
workloads:
- id: main
  kind: deployment
  primary: true
  containers:
  - name: metrics-server

    helm:
      resources: resources
  helm:
    labels: labels
    annotations: deploymentAnnotations
