name: metrics-server
title: Metrics server
type: infrastructure
scalable: false
hostname: metrics-server
containers:
- name: metrics-server

helm:
  name: metrics-server
  source: https://kubernetes-sigs.github.io/metrics-server
  chart: metrics-server/metrics-server
  version: 3.12.1
  configurations:
  - name: metrics-server
    annotations: deploymentAnnotations
    labels: labels
    resources: resources
