name: metrics-server
title: Metrics server
type: infrastructure
scalable: false
helm:
  name: metrics-server
  source: https://kubernetes-sigs.github.io/metrics-server
  chart: metrics-server/metrics-server
  version: 3.12.1

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{service.helm.release}}'
  kind: deployment
  primary: true
  helm:
    labels: podLabels
    annotations: deploymentAnnotations
  containers:
  - name: metrics-server
    helm:
      resources: resources
